import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const domain = 'https://nuvelloweb.com';
const modifiedDate = '2026-08-01';
const key = '24b0801f-cbde-421b-a03b-b3ab22c9eaf0';
const gtmHead = `<!-- Google Tag Manager --><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-KNH8LMBF');</script><!-- End Google Tag Manager -->`;
const gtmBody = `<!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KNH8LMBF" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!-- End Google Tag Manager (noscript) -->`;

const serviceLinks = [
  ['Web Design', '/services/web-design'], ['SEO', '/services/seo'], ['UI/UX Design', '/services/ui-ux'],
  ['Digital Marketing', '/services/digital-marketing'], ['E-Commerce', '/services/ecommerce'], ['Maintenance', '/services/maintenance']
];

const header = current => `<a class="skip-link" href="#main">Skip to content</a>
<div class="utility"><div class="wrap"><a href="tel:+13232199208">(323) 219-9208</a><a href="mailto:contact@nuvelloweb.com">contact@nuvelloweb.com</a><span>Los Angeles, CA</span></div></div>
<header class="site-header"><nav class="nav wrap" aria-label="Main navigation">
<a class="brand" href="/" aria-label="NuvelloWeb home"><img src="/assets/brand/nuvelloweb-logo-dark.svg" alt="NuvelloWeb Web Design and Marketing"></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="main-menu" aria-label="Open navigation"><span></span><span></span><span></span></button>
<ul class="nav-links" id="main-menu"><li><a href="/"${current === 'home' ? ' aria-current="page"' : ''}>Home</a></li><li class="dropdown"><a href="/about"${current === 'about' ? ' aria-current="page"' : ''}>About</a><ul class="dropdown-menu"><li><a href="/about">About Us</a></li><li><a href="/faq">FAQ</a></li></ul></li><li class="dropdown"><a href="/services"${current === 'services' ? ' aria-current="page"' : ''}>Services</a><ul class="dropdown-menu">${serviceLinks.map(([name, href]) => `<li><a href="${href}">${name}</a></li>`).join('')}</ul></li><li><a href="/blog"${current === 'blog' ? ' aria-current="page"' : ''}>Blog</a></li><li><a href="/contact"${current === 'contact' ? ' aria-current="page"' : ''}>Contact</a></li><li><a class="button" href="#quote">Get a Quote</a></li></ul></nav></header>`;

const footer = () => `<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><img class="footer-brand" src="/assets/brand/nuvelloweb-logo-dark.svg" alt="NuvelloWeb"><p>Web design and digital marketing for businesses ready to grow with intention.</p></div><div><h4>Company</h4><ul><li><a href="/about">About</a></li><li><a href="/services">Services</a></li><li><a href="/blog">Blog</a></li><li><a href="/faq">FAQ</a></li><li><a href="/contact">Contact</a></li></ul></div><div><h4>Services</h4><ul>${serviceLinks.map(([name, href]) => `<li><a href="${href}">${name}</a></li>`).join('')}</ul></div><div><h4>Contact</h4><ul><li><a href="tel:+13232199208">(323) 219-9208</a></li><li><a href="mailto:contact@nuvelloweb.com">contact@nuvelloweb.com</a></li><li>Los Angeles, CA</li><li><a href="https://instagram.com/nuvelloweb">Instagram</a></li><li><a href="https://www.linkedin.com/company/nuvello-web/">LinkedIn</a></li></ul></div></div><div class="footer-bottom"><span>© <span data-year></span> NuvelloWeb LLC. All rights reserved.</span><span>Los Angeles, California</span></div></div></footer><script src="/assets/site.js" defer></script>`;

const schema = ({ path, title, description, serviceName = '', article = null }) => {
  const labels = { about: 'About', services: 'Services', blog: 'Blog', contact: 'Contact', faq: 'FAQ', 'web-design': 'Web Design & Development', seo: 'SEO', 'ui-ux': 'UI/UX & Brand Design', 'digital-marketing': 'Digital Marketing', ecommerce: 'E-Commerce', maintenance: 'Maintenance & Support', 'small-business-website-cost-los-angeles': 'Small-Business Website Cost in Los Angeles', 'local-seo-los-angeles-starter-guide': 'Local SEO for Los Angeles Businesses' };
  const segments = path.split('/').filter(Boolean);
  const breadcrumb = [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${domain}/` }];
  segments.forEach((segment, index) => breadcrumb.push({ '@type': 'ListItem', position: index + 2, name: labels[segment] || segment, item: `${domain}/${segments.slice(0, index + 1).join('/')}` }));
  const webpage = { '@type': path === '/blog' ? ['WebPage', 'CollectionPage'] : 'WebPage', '@id': `${domain}${path}#webpage`, url: `${domain}${path}`, name: title, description, isPartOf: { '@id': `${domain}/#website` }, about: { '@id': `${domain}/#business` }, breadcrumb: { '@id': `${domain}${path}#breadcrumb` }, inLanguage: 'en-US', dateModified: modifiedDate };
  if (article) webpage.mainEntity = { '@id': `${domain}${path}#article` };
  const graph = [
    { '@type': 'WebSite', '@id': `${domain}/#website`, url: `${domain}/`, name: 'NuvelloWeb', publisher: { '@id': `${domain}/#business` }, inLanguage: 'en-US' },
    { '@type': ['ProfessionalService', 'LocalBusiness'], '@id': `${domain}/#business`, name: 'NuvelloWeb LLC', alternateName: 'NuvelloWeb', url: `${domain}/`, logo: { '@type': 'ImageObject', url: `${domain}/assets/brand/icon-512.png`, width: 512, height: 512 }, image: `${domain}/assets/og.png`, telephone: '+13232199208', email: 'contact@nuvelloweb.com', founder: { '@id': `${domain}/about#founder` }, address: { '@type': 'PostalAddress', addressLocality: 'Los Angeles', addressRegion: 'CA', addressCountry: 'US' }, areaServed: [{ '@type': 'City', name: 'Los Angeles' }, { '@type': 'Country', name: 'United States' }], sameAs: ['https://www.facebook.com/nuvellowebllc', 'https://www.linkedin.com/company/nuvello-web/', 'https://instagram.com/nuvelloweb'], knowsAbout: ['Web design', 'Web development', 'Search engine optimization', 'User experience design', 'Digital marketing', 'E-commerce'] },
    { '@type': 'Person', '@id': `${domain}/about#founder`, name: 'Benjamin Krikler', jobTitle: 'Founder', url: `${domain}/about`, image: `${domain}/assets/Images/BenKrikler2.jpeg`, worksFor: { '@id': `${domain}/#business` } },
    webpage,
    { '@type': 'BreadcrumbList', '@id': `${domain}${path}#breadcrumb`, itemListElement: breadcrumb }
  ];
  if (serviceName) graph.push({ '@type': 'Service', '@id': `${domain}${path}#service`, name: serviceName, url: `${domain}${path}`, description, provider: { '@id': `${domain}/#business` }, areaServed: [{ '@type': 'City', name: 'Los Angeles' }, { '@type': 'Country', name: 'United States' }] });
  if (article) {
    const post = { '@type': 'BlogPosting', '@id': `${domain}${path}#article`, headline: title, description, datePublished: article.datePublished, dateModified: modifiedDate, author: { '@id': `${domain}/about#founder` }, publisher: { '@id': `${domain}/#business` }, mainEntityOfPage: { '@id': `${domain}${path}#webpage` }, articleSection: article.section, keywords: article.keywords, inLanguage: 'en-US' };
    if (article.image) post.image = { '@type': 'ImageObject', url: `${domain}${article.image}`, width: article.imageWidth, height: article.imageHeight };
    graph.push(post);
  }
  return `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph })}</script>`;
};

const shell = ({ title, description, path, current, body, faqSchema = '', serviceName = '', article = null, ogImage = '/assets/og.png', ogWidth = 1200, ogHeight = 630 }) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${gtmHead}<title>${title}</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${domain}${path}"><link rel="icon" href="/assets/brand/favicon.svg?v=2" type="image/svg+xml"><link rel="alternate icon" href="/favicon.ico?v=2"><link rel="apple-touch-icon" href="/assets/brand/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest"><link rel="stylesheet" href="https://use.typekit.net/wrx5tvq.css"><link rel="stylesheet" href="/assets/site.css"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:url" content="${domain}${path}"><meta property="og:image" content="${domain}${ogImage}"><meta property="og:image:width" content="${ogWidth}"><meta property="og:image:height" content="${ogHeight}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${domain}${ogImage}">${article ? `<meta property="article:published_time" content="${article.datePublished}"><meta property="article:modified_time" content="${modifiedDate}"><meta property="article:section" content="${article.section}">` : ''}${schema({ path, title, description, serviceName, article })}${faqSchema}</head><body>${gtmBody}${header(current)}<main id="main">${body}</main>${footer()}</body></html>`;

const pageHero = (crumb, eyebrow, title, lead) => `<section class="hero page-hero"><div class="wrap"><div class="breadcrumb"><a href="/">Home</a><span>/</span>${crumb}</div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p class="lead">${lead}</p></div></section>`;

const form = (id, service = 'Not sure yet', heading = 'Tell us what you’re working on.') => `<section class="section quote" id="quote"><div class="wrap quote-grid"><div><span class="eyebrow">Start a conversation</span><h2>${heading}</h2><p>Share the goal, the roadblock, or even the rough idea. We’ll help turn it into a practical next step.</p><div class="promise">No-pressure discovery call</div><div class="promise">Clear scope and pricing</div><div class="promise">Response within one business day</div><div class="contact-options"><a href="tel:+13232199208">(323) 219-9208</a><a href="mailto:contact@nuvelloweb.com">contact@nuvelloweb.com</a></div></div><form class="lead-form" action="https://api.web3forms.com/submit" method="post"><input type="hidden" name="access_key" value="${key}"><input type="hidden" name="subject" value="New ${service} inquiry from NuvelloWeb.com"><input type="hidden" name="from_name" value="NuvelloWeb Website"><input class="honeypot" type="checkbox" name="botcheck" tabindex="-1" autocomplete="off"><div class="form-grid"><div class="field"><label for="${id}-name">Name</label><input id="${id}-name" name="name" autocomplete="name" required></div><div class="field"><label for="${id}-email">Email</label><input id="${id}-email" type="email" name="email" autocomplete="email" required></div><div class="field"><label for="${id}-phone">Phone</label><input id="${id}-phone" type="tel" name="phone" autocomplete="tel"></div><div class="field"><label for="${id}-service">Service</label><select id="${id}-service" name="service">${[service, ...serviceLinks.map(([name]) => name), 'Not sure yet'].filter((v, i, a) => a.indexOf(v) === i).map(v => `<option${v === service ? ' selected' : ''}>${v}</option>`).join('')}</select></div><div class="field full"><label for="${id}-message">Project details</label><textarea id="${id}-message" name="message" required></textarea></div></div><button class="button orange" type="submit">Send project details</button><p class="form-note">By submitting, you agree that NuvelloWeb may contact you about this request.</p><div class="form-status" role="status" aria-live="polite"></div></form></div></section>`;

const insightsPromo = (heading = 'Practical thinking for better digital decisions.') => `<section class="section compact insights-promo"><div class="wrap insights-promo-inner"><div><span class="eyebrow">From the NuvelloWeb blog</span><h2>${heading}</h2><p>Clear guidance on websites, search visibility, user experience, and the choices that shape a stronger digital foundation.</p></div><a class="button ghost button-arrow" href="/blog">Visit the blog</a></div></section>`;

const faq = items => `<div class="faq-list">${items.map(([q, a], i) => `<div class="faq-item"><button class="faq-question" aria-expanded="${i === 0 ? 'true' : 'false'}">${q}</button><div class="faq-answer"><div><p>${a}</p></div></div></div>`).join('')}</div>`;
const faqJson = items => `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: items.map(([q,a]) => ({ '@type':'Question', name:q, acceptedAnswer:{ '@type':'Answer', text:a.replace(/<[^>]*>/g,'') } })) })}</script>`;

const aboutBody = `${pageHero('About', 'About NuvelloWeb', 'Small studio.<br><span class="accent">Serious ownership.</span>', 'NuvelloWeb is a founder-led Los Angeles web and marketing studio built for businesses that want direct communication, thoughtful work, and fewer layers.')}
<section class="section"><div class="wrap split"><div><span class="eyebrow">The story</span><h2>Built from frustration with the usual agency experience.</h2><p>Too many businesses pay for attractive websites that never become useful business tools. Others get trapped between a disappearing freelancer and an agency process so layered that the people doing the work feel unreachable.</p><p>NuvelloWeb exists in the middle: the craft and attention of a focused studio, paired with the strategy and range needed to support a growing business.</p><p>We use the tools that fit the project. Sometimes that means a flexible CMS or commerce platform. Sometimes it means a lean custom build. The recommendation follows the goal—not ideology.</p></div><figure class="founder"><img src="/assets/Images/BenKrikler2.jpeg" alt="Benjamin Krikler, founder of NuvelloWeb"><figcaption><strong>Benjamin Krikler</strong><span>Founder, NuvelloWeb LLC</span></figcaption></figure></div></section>
<section class="section alt"><div class="wrap"><header class="section-head center"><span class="eyebrow">How we work</span><h2>Principles that show up in the work.</h2></header><div class="grid three"><div class="card"><span class="icon">01</span><h3>Clarity first</h3><p>Clear recommendations, plain-language explanations, and no mystery around scope or price.</p></div><div class="card"><span class="icon">02</span><h3>Outcomes over ornament</h3><p>Strong creative matters, but it has to serve the customer journey and the business goal.</p></div><div class="card"><span class="icon">03</span><h3>Direct accountability</h3><p>You know who owns the work, where it stands, and what happens next.</p></div><div class="card"><span class="icon">04</span><h3>Right-sized solutions</h3><p>No unnecessary complexity. No forcing every project into the same platform or package.</p></div><div class="card"><span class="icon">05</span><h3>Built to evolve</h3><p>Your digital presence should support the next phase, not become tomorrow’s constraint.</p></div><div class="card"><span class="icon">06</span><h3>Partnership mindset</h3><p>We bring a point of view, listen carefully, and make decisions with you—not at you.</p></div></div></div></section>${insightsPromo('See the thinking behind the work.')}${form('about','Not sure yet','Let’s build something worth growing.')}`;

const services = [
  {slug:'web-design', name:'Web Design & Development', eyebrow:'Web design services', title:'Websites built to <span class="accent">perform.</span>', lead:'Fast, credible, easy to use, and shaped around the next action you want a visitor to take.', intro:'From a focused landing page to a full business website, we connect message, structure, visual design, and development into one cohesive customer experience.', features:[['Business websites','Strategic, conversion-focused sites that make the offer clear and the next step easy.'],['WordPress development','Flexible sites that give your team practical control over content.'],['Custom development','Lean, purpose-built front ends and applications when the project needs more than a CMS.'],['Landing pages','Campaign pages focused on one audience, one offer, and one measurable action.'],['Website redesigns','A clearer structure and stronger experience without losing what already works.'],['Performance & accessibility','Responsive, fast-loading experiences built to work for more people.']], process:[['Discovery','Goals, audience, content, competitors, and technical needs.'],['Structure','Sitemap, page priorities, and the path from entry to action.'],['Design','A visual system that feels distinct, credible, and usable.'],['Development','Responsive implementation with the appropriate platform and integrations.'],['Quality assurance','Content, forms, links, devices, accessibility, and launch checks.'],['Launch','Deployment, analytics, handoff, and a clear plan for what comes next.']], faqs:[['Do you only build custom-coded websites?','No. We recommend the right approach for the project. That may be a lean custom build, WordPress, Shopify, WooCommerce, or another well-supported platform.'],['How long does a website take?','A focused site may take a few weeks; a larger or more complex build takes longer. Your proposal includes a realistic schedule based on scope and content readiness.'],['Will I own the website?','Yes. Once the agreed project balance is paid, you receive ownership of the finished work and access to the systems used to run it.']]},
  {slug:'seo', name:'SEO', eyebrow:'Search engine optimization', title:'Get found by people already <span class="accent">looking.</span>', lead:'Technical, local, and content improvements that make your business easier for search engines—and customers—to understand.', intro:'SEO is not a bag of tricks. It is the ongoing work of making your site technically sound, locally relevant, genuinely useful, and easier to discover for the searches that matter.', features:[['Local SEO','Google Business Profile, citations, location signals, and pages built around local intent.'],['Technical SEO','Crawlability, indexing, site speed, structured data, redirects, and sitemap health.'],['On-page SEO','Search-informed page structure, titles, descriptions, headings, internal links, and content.'],['Content strategy','Useful topics mapped to customer questions and the stages of the buying journey.'],['E-commerce SEO','Category, collection, product, and technical improvements for online stores.'],['Reporting & refinement','Readable reporting tied to visibility, qualified traffic, and business outcomes.']], process:[['Audit','Find technical barriers, content gaps, local weaknesses, and quick wins.'],['Research','Map audience language and search intent to the right pages.'],['Prioritize','Turn findings into a practical sequence based on impact and effort.'],['Improve','Implement technical, on-page, local, and content changes.'],['Measure','Track rankings, traffic quality, leads, and key behavior.'],['Refine','Build on what works and adapt as the market and search results change.']], faqs:[['How long before SEO works?','Meaningful movement often takes several months, depending on the market, the site’s current condition, and the strength of competing results.'],['Can you guarantee first place on Google?','No credible provider can guarantee a specific organic ranking. We can guarantee transparent work, sound priorities, and reporting you can understand.'],['Do I need ongoing SEO?','Some technical projects are finite, but competitive visibility usually benefits from ongoing content, authority, local profile, and measurement work.']]},
  {slug:'ui-ux', name:'UI/UX & Brand Design', eyebrow:'Design services', title:'Design that works.<br><span class="accent">Looks that connect.</span>', lead:'Interfaces and brand systems that help people understand, trust, and use what you offer.', intro:'Good design reduces friction. It clarifies hierarchy, makes choices easier, and creates a recognizable experience across the moments where customers meet your brand.', features:[['UX strategy & wireframes','User flows and page structures built around real tasks and decision points.'],['Interface design','Responsive screens and reusable components with consistent interaction patterns.'],['Brand identity','Logo refinement, color, typography, and guidelines that create a coherent presence.'],['Design systems','Reusable foundations that make future pages and product features easier to build.'],['Campaign creative','Landing pages, ads, social assets, presentations, and supporting collateral.'],['Design audits','Practical recommendations for improving clarity, consistency, and conversion.']], process:[['Discover','Define the audience, business goal, use cases, and creative constraints.'],['Research','Review competitors, references, user expectations, and existing brand equity.'],['Structure','Create flows, wireframes, and content hierarchy before visual polish.'],['Design','Build the visual language and apply it to high-value screens or assets.'],['Refine','Use focused feedback rounds to sharpen the strongest direction.'],['Handoff','Deliver organized files, specifications, and practical guidance for ongoing use.']], faqs:[['Can you work with our existing brand?','Yes. We can extend a strong existing system, refine one that feels inconsistent, or build a new direction when the old identity no longer fits.'],['Do you provide editable source files?','Yes. Final deliverables and source formats are defined in the proposal so your team knows exactly what it will receive.'],['Can you design without developing?','Yes. Design-only engagements can include research, wireframes, high-fidelity screens, systems, and developer-ready handoff.']]},
  {slug:'digital-marketing', name:'Digital Marketing', eyebrow:'Digital marketing', title:'Campaigns built for <span class="accent">useful attention.</span>', lead:'Focused strategy, creative, and measurement that connect the right audience to the right next step.', intro:'More traffic is not the goal if it is the wrong traffic. We connect channel, message, landing experience, and follow-up so marketing activity has a better chance to become pipeline.', features:[['Paid search','Intent-led Google Ads campaigns with focused landing experiences and conversion tracking.'],['Paid social','Audience, offer, creative, and retargeting strategies for Meta and other relevant platforms.'],['Email marketing','Nurture, reactivation, and campaign messages designed around meaningful segments.'],['Content campaigns','Useful content and promotional assets aligned to customer questions and decisions.'],['Landing pages','Fast, campaign-specific pages built to improve message match and conversion.'],['Analytics & reporting','Practical measurement that distinguishes activity from actual progress.']], process:[['Audit','Review the offer, audience, existing channels, tracking, and economics.'],['Strategy','Choose priorities, goals, messages, and the role of each channel.'],['Build','Create campaigns, audiences, creative, landing pages, and tracking.'],['Launch','Go live with controlled budgets and clear conversion events.'],['Optimize','Improve targeting, creative, message match, and post-click experience.'],['Report','Explain what happened, what it means, and what to do next.']], faqs:[['Which channels should we use?','That depends on audience behavior, intent, offer, margins, and available creative. We recommend the smallest useful channel mix first.'],['What ad budget do I need?','The right starting budget depends on click costs, conversion rate, sales value, and learning goals. We set expectations before launch rather than inventing a universal minimum.'],['Do you create landing pages too?','Yes. The post-click experience is often as important as the ad, so landing page strategy and implementation can be included.']]},
  {slug:'ecommerce', name:'E-Commerce', eyebrow:'E-commerce development', title:'Stores built to <span class="accent">sell with less friction.</span>', lead:'Shopify and WooCommerce experiences that make discovery, confidence, and checkout feel natural.', intro:'A strong store balances brand, merchandising, content, operations, and conversion. We shape the full buying experience—not just the homepage.', features:[['Shopify stores','Theme setup, customization, product structure, apps, and conversion-focused storefronts.'],['WooCommerce stores','Flexible WordPress commerce builds with greater control over content and hosting.'],['Store redesigns','Sharper merchandising, navigation, product pages, and checkout flow.'],['Platform migrations','Careful moves between platforms with products, customers, orders, and SEO in mind.'],['Payments & shipping','Practical configuration for payment methods, taxes, shipping, and notifications.'],['Conversion optimization','Measurement and iterative improvements across product discovery and checkout.']], process:[['Discovery','Products, customers, operations, platform needs, and growth goals.'],['Architecture','Collections, categories, navigation, filters, and content priorities.'],['Design','A store system that supports the brand and makes products easier to choose.'],['Build','Theme implementation, catalog setup, integrations, and key automations.'],['Test','Devices, payments, tax, shipping, notifications, accounts, and analytics.'],['Launch & support','Controlled launch, monitoring, documentation, and ongoing improvement options.']], faqs:[['Should I choose Shopify or WooCommerce?','Shopify is often ideal for operational simplicity. WooCommerce can be a better fit when content flexibility and hosting control matter more. We weigh the tradeoffs with you.'],['Can you migrate my existing store?','Yes. Migration scope depends on the source platform and the amount of product, customer, order, content, and SEO data involved.'],['Do you set up payments and shipping?','Yes. We configure the agreed payment, tax, and shipping workflows and test the customer-facing experience before launch.']]},
  {slug:'maintenance', name:'Maintenance & Support', eyebrow:'Website care plans', title:'Your site should keep working <span class="accent">after launch.</span>', lead:'Updates, backups, security, performance checks, and practical support when your business needs a change.', intro:'A website is an operating asset. Care plans keep the core software healthy, catch issues sooner, and give you a reliable place to send the updates that do not justify a new project.', features:[['Core updates','Managed updates for the CMS, plugins, themes, and compatible dependencies.'],['Backups','Scheduled backups with retention appropriate to the care level.'],['Security monitoring','Routine monitoring and response for common website threats and suspicious activity.'],['Performance checks','Ongoing attention to uptime, speed, broken pages, and form health.'],['Content support','A dependable channel for routine copy, image, and page updates.'],['Priority help','Faster response windows and reserved support time on higher plans.']], process:[['Baseline review','Document the site, hosting, access, dependencies, and known issues.'],['Stabilize','Create backups, apply safe updates, and address immediate health concerns.'],['Monitor','Watch the agreed health signals and recurring maintenance schedule.'],['Update','Handle routine platform and content changes within the plan.'],['Report','Summarize completed work and issues that need a decision.'],['Improve','Recommend focused enhancements when the data or business priorities support them.']], faqs:[['Can you maintain a site you did not build?','Usually, yes. We begin with a paid or complimentary technical review depending on complexity, then confirm what can be supported safely.'],['Are redesigns included?','Care plans cover routine maintenance and the included support time. Larger design or development work is scoped separately.'],['Do unused support hours roll over?','Plan-specific rollover terms are confirmed in the agreement so expectations are clear before service begins.']]}
];

const serviceBody = s => `${pageHero('<a href="/services">Services</a><span>/</span>'+s.name, s.eyebrow, s.title, s.lead)}<section class="section"><div class="wrap split"><div><span class="eyebrow">The approach</span><h2>${s.intro}</h2></div><div><p>Every engagement starts with the business context and the customer experience. From there, we define the smallest complete solution that can do the job well and support what comes next.</p><ul class="check-list"><li>Clear deliverables and decision points</li><li>Responsive, accessible, and performance-minded</li><li>Ownership and handoff defined upfront</li><li>Direct communication throughout</li></ul></div></div></section><section class="section alt"><div class="wrap"><header class="section-head"><span class="eyebrow">Capabilities</span><h2>What this can include.</h2></header><div class="grid three">${s.features.map(([h,p],i)=>`<div class="card"><span class="icon">${String(i+1).padStart(2,'0')}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></div></section><section class="section"><div class="wrap split"><header class="section-head"><span class="eyebrow">Process</span><h2>A clear path from problem to progress.</h2><p>The exact scope changes. The accountability does not.</p></header><div class="process">${s.process.map(([h,p])=>`<div class="process-item"><div><h3>${h}</h3><p>${p}</p></div></div>`).join('')}</div></div></section>${s.slug === 'maintenance' ? `<section class="section alt"><div class="wrap"><header class="section-head center"><span class="eyebrow">Care plans</span><h2>Choose the level of coverage that fits.</h2><p>Final recommendations follow a technical review of your site.</p></header><div class="grid three"><div class="card"><span class="kicker">Essential</span><h3>Basic Care</h3><div class="price">$99 <small>/ month</small></div><ul class="check-list"><li>Monthly managed updates</li><li>Scheduled backups</li><li>Uptime monitoring</li><li>Email support</li></ul></div><div class="card featured"><span class="badge">Most popular</span><h3>Growth Care</h3><div class="price">$199 <small>/ month</small></div><ul class="check-list"><li>More frequent updates</li><li>Security and performance checks</li><li>Routine content support</li><li>Priority response</li></ul></div><div class="card"><span class="kicker">Expanded</span><h3>Agency Care</h3><div class="price">$349 <small>/ month</small></div><ul class="check-list"><li>Highest monitoring cadence</li><li>Expanded support time</li><li>Monthly health summary</li><li>Priority scheduling</li></ul></div></div></div></section>` : ''}<section class="section alt"><div class="narrow"><header class="section-head"><span class="eyebrow">Common questions</span><h2>Good things to know.</h2></header>${faq(s.faqs)}</div></section>${insightsPromo('Learn before you commit to the next move.')}${form(s.slug,s.name,s.slug === 'seo' ? 'Get a clearer SEO plan.' : `Let’s talk about ${s.name.toLowerCase()}.`)}`;

const serviceHubBody = `${pageHero('Services','Full-service digital studio','One partner.<br><span class="accent">A connected digital system.</span>','Web, design, search, commerce, marketing, and ongoing support—planned together around the customer journey.')}
<section class="section"><div class="wrap"><header class="section-head"><span class="eyebrow">Core services</span><h2>Start with what the business needs now.</h2><p>Each service stands on its own. Together, they form a stronger system from first impression to qualified inquiry.</p></header><div class="grid three">${services.map((s,i)=>`<a class="card" href="/services/${s.slug}"><span class="icon">${String(i+1).padStart(2,'0')}</span><h3>${s.name}</h3><p>${s.lead}</p><span class="card-link">Explore service</span></a>`).join('')}</div></div></section>
<section class="section alt"><div class="wrap split"><div><span class="eyebrow">Not sure where to start?</span><h2>Bring the business problem, not a preselected deliverable.</h2><p>You do not need to know whether you need SEO, a redesign, a landing page, or a different platform. We’ll look at the goal, the bottleneck, and what is already working before recommending the next move.</p></div><div class="process"><div class="process-item"><div><h3>Diagnose</h3><p>Clarify the constraint and the real opportunity.</p></div></div><div class="process-item"><div><h3>Prioritize</h3><p>Sequence the work by impact, urgency, and budget.</p></div></div><div class="process-item"><div><h3>Execute</h3><p>Build the right first phase without losing sight of the larger system.</p></div></div></div></div></section>${insightsPromo('Research the options before choosing the scope.')}${form('services','Not sure yet','Let’s find the right starting point.')}`;

const contactBody = `${pageHero('Contact','Contact NuvelloWeb','Let’s make the next move <span class="accent">clear.</span>','Tell us about the business, the project, or the thing that is not working. You will hear back within one business day.')}
<section class="section"><div class="wrap grid three"><div class="card"><span class="kicker">Call</span><h3><a href="tel:+13232199208">(323) 219-9208</a></h3><p>For a quick first conversation about fit and timing.</p></div><div class="card"><span class="kicker">Email</span><h3><a href="mailto:contact@nuvelloweb.com">contact@nuvelloweb.com</a></h3><p>Send context, links, or a project brief whenever you are ready.</p></div><div class="card"><span class="kicker">Based in</span><h3>Los Angeles, CA</h3><p>Serving local businesses and remote clients across the United States.</p></div></div></section>${form('contact','Not sure yet','Tell us what’s next.')}`;

const generalFaqs = [['What makes NuvelloWeb different?','NuvelloWeb is a founder-led studio. You work directly with the person responsible for strategy and delivery, with clear scope and fewer layers between the conversation and the work.'],['Do you use templates or page builders?','Sometimes a well-supported theme, platform, or builder is the right business choice; other projects benefit from a more custom approach. We recommend tools based on goals, budget, ownership, and long-term maintenance.'],['Where are you located?','NuvelloWeb is based in Los Angeles, California, and works with both local and remote clients.'],['How does a project start?','It begins with a discovery conversation. We clarify goals, audience, constraints, scope, and timing before proposing the work.'],['How long does a website project take?','A focused website may take a few weeks. Larger sites, custom functionality, commerce, or content-heavy projects take longer. Your proposal includes a schedule tailored to the actual scope.'],['How much does a website cost?','Pricing depends on the number of pages, content needs, platform, integrations, and level of custom work. You receive a clear scope and price before work begins. <a href="/blog/small-business-website-cost-los-angeles">Read our full Los Angeles website pricing guide.</a>'],['Will my site work on phones and tablets?','Yes. Responsive behavior is part of every website engagement, along with modern browser and usability checks.'],['Will I be able to edit the site?','When content editing is an important requirement, we recommend a platform and setup that gives your team practical control. Training or documentation can be included.'],['Do you offer hosting?','We can advise on hosting and configure deployment as part of a project. Hosting ownership, billing, backups, and support responsibilities are documented clearly.'],['Can you improve an existing website?','Yes. We can audit, redesign, migrate, optimize, or selectively improve an existing site depending on its condition and your goals.'],['Do you require a long contract?','Project work is typically scoped with defined phases and payment terms. Ongoing SEO, marketing, or maintenance uses a separate agreement with clearly stated terms.'],['What happens after launch?','You receive the agreed handoff and access. Ongoing maintenance, marketing, SEO, and improvement support are available when needed.']];
const faqBody = `${pageHero('FAQ','Frequently asked questions','Clear answers before we <span class="accent">start.</span>','The practical details about process, platforms, pricing, ownership, and working together.')}
<section class="section"><div class="narrow">${faq(generalFaqs)}</div></section>${insightsPromo('Go deeper than the quick answer.')}${form('faq','Not sure yet','Still have a question?')}`;

const articleSlug = 'small-business-website-cost-los-angeles';
const articlePath = `/blog/${articleSlug}`;
const articleTitle = 'How Much Does a Small-Business Website Cost in Los Angeles?';
const articleDescription = 'A practical Los Angeles guide to small-business website costs, pricing tiers, scope drivers, hidden expenses, and comparing web design proposals.';
const articleImage = '/assets/downtown-los-angeles-website-cost-guide.jpg';
const articlePublishedDate = '2026-07-20';
const articlePublishedLabel = 'July 20, 2026';
const articleFaqs = [
  ['What is a realistic budget for a small-business website in Los Angeles?','For a focused professional marketing website, $3,000 to $8,000 is a useful planning range. A more custom site with strategy, copywriting, integrations, or advanced functionality can move into the $8,000 to $20,000 range or higher.'],
  ['Can a small business get a good website for less than $3,000?','Yes, when the scope is simple, the business supplies finished content, and a proven template or platform does most of the structural work. Be clear about what is excluded and how future changes will be handled.'],
  ['Should SEO be included in the website price?','A professional build should include foundational technical and on-page SEO such as crawlable pages, titles, descriptions, heading structure, performance basics, and redirects when needed. Ongoing content, local SEO, and authority work are usually separate.'],
  ['How long does a small-business website take to build?','A focused site commonly takes four to ten weeks. Content readiness, feedback speed, page count, custom functionality, and the number of decision-makers can shorten or extend the schedule.']
];

const localSeoSlug = 'local-seo-los-angeles-starter-guide';
const localSeoPath = `/blog/${localSeoSlug}`;
const localSeoTitle = 'Local SEO for Los Angeles Businesses: A Practical Starter Guide';
const localSeoDescription = 'A practical local SEO guide for Los Angeles businesses covering Google Business Profile, website signals, reviews, citations, content, and measurement.';
const localSeoPublishedDate = '2026-07-27';
const localSeoPublishedLabel = 'July 27, 2026';
const localSeoFaqs = [
  ['How long does local SEO take?','Basic profile and website corrections can improve clarity quickly, but meaningful growth in a competitive Los Angeles market usually takes months of consistent work. Timing depends on the starting point, category, location, competition, and reputation.'],
  ['Do I need a Los Angeles street address?','Not always. An eligible service-area business can use a real operating location and hide the address if customers are not served there. The business must still make in-person contact with customers and follow Google’s eligibility rules.'],
  ['Should every page target Los Angeles?','No. Use local language where it helps the reader. Core service pages, contact details, case studies, and select location content can establish relevance without turning every sentence into a keyword exercise.'],
  ['Can I pay Google for a better local ranking?','No. Ads can buy sponsored visibility, but Google states that businesses cannot request or pay for better local organic ranking.']
];

const blogBody = `<section class="hero blog-hero"><div class="wrap"><div class="blog-hero-grid"><div><div class="breadcrumb"><a href="/">Home</a><span>/</span>Blog</div><span class="eyebrow">NuvelloWeb insights</span><h1>Ideas for better websites.<br><span class="accent">And better decisions.</span></h1><p class="lead">Practical guidance for business owners navigating web design, SEO, digital marketing, e-commerce, and the choices that connect them.</p><div class="actions"><a class="button orange" href="${localSeoPath}">Read the latest article</a><a class="button ghost" href="#topics">Browse topics</a></div></div><figure class="blog-hero-media"><img src="/assets/los-angeles-night-traffic-blog-hero.jpg" alt="Los Angeles streets and freeway light trails at night"><figcaption>Built in Los Angeles. Written for businesses everywhere.</figcaption></figure></div></div></section>
<section class="section alt" id="articles"><div class="wrap"><header class="section-head"><span class="eyebrow">Latest insights</span><h2>Start with a practical question.</h2><p>Clear guidance for the decisions that shape a stronger website and a more visible local business.</p></header><div class="post-grid"><article class="post-card text-led"><div class="post-card-body"><span class="status-pill">New guide</span><p class="empty-kicker">Local SEO · Los Angeles</p><h3><a href="${localSeoPath}">${localSeoTitle}</a></h3><p>Set up the essential local search signals: an accurate Google Business Profile, useful service pages, genuine reviews, consistent listings, and measurement that connects visibility to leads.</p><div class="article-meta"><span>${localSeoPublishedLabel}</span><span>7 minute read</span></div><a class="button ghost button-arrow" href="${localSeoPath}">Read the guide</a></div></article><article class="post-card"><a class="post-card-media" href="${articlePath}" aria-label="Read ${articleTitle}"><img src="${articleImage}" alt="Aerial view of downtown Los Angeles"></a><div class="post-card-body"><p class="empty-kicker">Web design pricing · Los Angeles</p><h3><a href="${articlePath}">${articleTitle}</a></h3><p>Price ranges, scope variables, hidden costs, and a better way to compare what different website proposals actually include.</p><div class="article-meta"><span>${articlePublishedLabel}</span><span>9 minute read</span></div><a class="button ghost button-arrow" href="${articlePath}">Read the article</a></div></article></div></div></section>
<section class="section" id="topics"><div class="wrap"><header class="section-head"><span class="eyebrow">What we cover</span><h2>Clear thinking across the digital foundation.</h2><p>Topics are chosen around the questions clients ask before, during, and after a project.</p></header><div class="grid three"><div class="card topic-card"><span class="icon">01</span><h3>Web design & UX</h3><p>Budgets, redesign decisions, platforms, accessibility, conversion paths, and the details that make a site useful.</p><span class="tag">Planning</span><span class="tag">User experience</span></div><div class="card topic-card"><span class="icon">02</span><h3>SEO & discovery</h3><p>Local visibility, technical foundations, content strategy, AI search, and how customers find credible answers.</p><span class="tag">Local SEO</span><span class="tag">AI search</span></div><div class="card topic-card"><span class="icon">03</span><h3>Growth & operations</h3><p>Maintenance, e-commerce, analytics, marketing choices, and what happens after the launch announcement.</p><span class="tag">Measurement</span><span class="tag">Maintenance</span></div></div></div></section>
<section class="section compact blog-note"><div class="narrow center"><span class="eyebrow">No noise for the sake of frequency</span><h2>Fewer posts. More signal.</h2><p>We publish when a question deserves a complete answer—not because a content calendar says the week is empty. Every article is built to help someone make a clearer decision.</p><div class="actions center"><a class="button ghost" href="/faq">Read the FAQ</a><a class="button orange button-arrow" href="#quote">Suggest a question</a></div></div></section>${form('blog','Not sure yet','Have a question worth answering?')}`;

const articleBody = `<section class="article-hero"><div class="article-heading"><div class="breadcrumb"><a href="/">Home</a><span>/</span><a href="/blog">Blog</a><span>/</span>Website cost</div><span class="eyebrow">Web design pricing · Los Angeles</span><h1>${articleTitle}</h1><p class="lead">A clear planning guide for understanding price ranges, seeing what actually changes the scope, and comparing proposals without paying twice for missing work.</p><div class="article-meta"><span>By <a href="/about">Benjamin Krikler</a></span><time datetime="${articlePublishedDate}">${articlePublishedLabel}</time><span>9 minute read</span></div></div></section>
<figure class="article-hero-image"><img src="${articleImage}" alt="Aerial view of downtown Los Angeles and its business district"><figcaption>Downtown Los Angeles. Website budgets vary for the same reason buildings do: the requirements beneath the surface are different.</figcaption></figure>
<section class="section article-section"><div class="wrap article-layout"><aside class="article-toc" aria-label="Article contents"><span class="kicker">In this guide</span><nav><a href="#short-answer">The short answer</a><a href="#price-ranges">Planning ranges</a><a href="#scope-drivers">What changes the price</a><a href="#hidden-costs">Hidden costs</a><a href="#compare-proposals">Compare proposals</a><a href="#choose-budget">Choose a budget</a><a href="#los-angeles">Los Angeles context</a><a href="#faqs">FAQs</a></nav></aside><article class="article-prose">
<section id="short-answer"><p class="article-lede"><strong>The short answer:</strong> a professional small-business website in Los Angeles often falls between <strong>$3,000 and $20,000</strong>. A focused brochure-style site may land near the lower end. Strategy, custom design, original content, e-commerce, integrations, or complex functionality move the investment higher.</p><div class="answer-box"><span class="kicker">A useful starting point</span><p>Plan around the job the website needs to do—not a universal page price. A five-page site built to establish credibility is a different project from a five-page site expected to generate qualified leads, rank in a competitive market, integrate with business systems, and support years of content.</p></div><p>Industry data is broad for exactly that reason. <a href="https://clutch.co/web-designers/pricing" rel="noopener">Clutch’s 2026 web design pricing guide</a> reports reviewed agency projects spanning roughly $2,000 to $100,000, with common hourly rates of $100–$149. The useful question is not “What does a website cost?” It is “What complete scope will solve this business problem?”</p></section>
<section id="price-ranges"><h2>Practical website planning ranges</h2><p>These are planning ranges, not a NuvelloWeb quote or a promise about every provider. They help you identify which kind of engagement you are actually comparing.</p><div class="price-grid"><div class="price-tier"><span class="kicker">DIY or assisted DIY</span><strong>$300–$2,000</strong><p>A website builder, template, domain, and basic tools. Best when the site is simple and the owner can supply the strategy, copy, images, setup, and ongoing time.</p></div><div class="price-tier"><span class="kicker">Focused professional site</span><strong>$3,000–$8,000</strong><p>A polished marketing site with a clear structure, responsive design, core pages, contact forms, basic search foundations, and a manageable content system.</p></div><div class="price-tier"><span class="kicker">Custom growth website</span><strong>$8,000–$20,000</strong><p>Deeper strategy, custom layouts, multiple services or audiences, conversion planning, content support, integrations, stronger SEO preparation, and broader quality assurance.</p></div><div class="price-tier"><span class="kicker">Advanced or commerce build</span><strong>$15,000–$50,000+</strong><p>E-commerce, member areas, complex catalogs, custom tools, migrations, advanced integrations, or workflows that require more discovery, development, testing, and launch support.</p></div></div><p>A lower number is not automatically a bargain, and a higher number is not automatically better. The value depends on what is included, how well the work fits the goal, and whether the finished site is usable by the business after launch.</p></section>
<section id="scope-drivers"><h2>Eight things that change the price</h2><ol class="article-steps"><li><h3>Page count and page type</h3><p>Ten pages based on three reusable layouts are simpler than ten pages that each require unique strategy, content, design, or functionality.</p></li><li><h3>Content readiness</h3><p>Finished, approved copy keeps a project moving. Messaging strategy, interviews, copywriting, photography selection, and content entry add valuable work—and time.</p></li><li><h3>Template versus custom design</h3><p>A proven design system can reduce cost. A distinctive visual direction with custom components, interaction design, and multiple review rounds requires more design and development effort.</p></li><li><h3>Features and integrations</h3><p>Booking, payments, gated content, multilingual pages, CRM connections, product catalogs, calculators, and custom forms need definition, implementation, testing, and maintenance planning.</p></li><li><h3>Platform and editing needs</h3><p>A simple static site has different requirements from WordPress, Shopify, WooCommerce, or a custom content system. The right choice depends on who will edit it and what must evolve.</p></li><li><h3>Search and migration work</h3><p>Keyword research, redirect mapping, structured data, local landing pages, content consolidation, and protecting existing rankings can materially change a redesign scope.</p></li><li><h3>Quality assurance</h3><p>Responsive behavior, accessibility, speed, forms, analytics, browser testing, and launch checks are part of professional delivery—even though they are less visible than the homepage.</p></li><li><h3>Timeline and decision-making</h3><p>Rush work, delayed content, many stakeholders, or unclear approval ownership can add coordination and rework. A realistic schedule protects both the budget and the result.</p></li></ol></section>
<section id="hidden-costs"><h2>Costs that are easy to miss</h2><p>A proposal can look inexpensive because important work sits outside the number. Ask whether the following are included now, billed separately, or left to you:</p><ul class="check-list article-checks"><li>Domain registration, hosting, backups, and security</li><li>Copywriting, editing, photography, and image licensing</li><li>Logo refinement or broader brand work</li><li>Premium themes, plugins, apps, and software subscriptions</li><li>Content migration and redirect planning</li><li>Analytics, conversion tracking, and form delivery</li><li>Training, documentation, and post-launch support</li><li>Maintenance, updates, and future content changes</li><li>Ongoing SEO, paid marketing, or conversion improvement</li></ul><div class="article-callout"><h3>Separate project cost from operating cost.</h3><p>The build gets the website launched. Hosting, software, maintenance, content, and marketing keep it useful. A responsible proposal makes both categories visible before you commit.</p></div></section>
<section id="compare-proposals"><h2>How to compare website proposals fairly</h2><p>Two quotes can use the same phrase—“custom website”—while describing very different work. Compare the deliverables beneath the label.</p><div class="proposal-table"><table><thead><tr><th>Area</th><th>Questions to ask</th></tr></thead><tbody><tr><td>Strategy</td><td>Is discovery included? Who defines the audience, goals, sitemap, and conversion path?</td></tr><tr><td>Content</td><td>Who writes, edits, supplies, approves, and enters the copy and images?</td></tr><tr><td>Design</td><td>Is the work template-based or custom? How many page layouts and review rounds are included?</td></tr><tr><td>Development</td><td>What platform is used? What features, integrations, and responsive behavior are included?</td></tr><tr><td>SEO</td><td>Are titles, descriptions, heading structure, redirects, indexing controls, and structured data addressed?</td></tr><tr><td>Launch</td><td>Who handles the domain, hosting, analytics, forms, quality checks, and deployment?</td></tr><tr><td>Ownership</td><td>Who owns the website, accounts, content, design files, licenses, and access after final payment?</td></tr><tr><td>Support</td><td>What happens after launch? Is training, warranty work, maintenance, or response time defined?</td></tr></tbody></table></div><p>Ask each provider to state exclusions as clearly as inclusions. A complete proposal is easier to trust because it tells you where its responsibility ends.</p></section>
<section id="choose-budget"><h2>How to choose the right budget</h2><p>Start with business value and risk rather than an arbitrary number.</p><div class="question-stack"><div><span>01</span><p><strong>What must the site accomplish in the next 12 months?</strong> Credibility, qualified inquiries, bookings, sales, recruiting, customer education, or something else?</p></div><div><span>02</span><p><strong>What is one new customer worth?</strong> A site supporting a $500 service and one supporting a $50,000 engagement have different economics.</p></div><div><span>03</span><p><strong>What can be phased?</strong> Launch the smallest complete version, then add content, integrations, or campaigns when the foundation is working.</p></div><div><span>04</span><p><strong>Who owns content and decisions?</strong> Assigning one accountable person reduces delays, contradictory feedback, and expensive rework.</p></div></div><p>If the budget is tight, reduce scope before reducing fundamentals. Fewer excellent pages are usually more useful than a larger site filled with generic copy, unfinished sections, or features no one maintains.</p></section>
<section id="los-angeles"><h2>Does being in Los Angeles change the cost?</h2><p>Sometimes—but location is not the main driver. Los Angeles has a deep market of freelancers, focused studios, specialist firms, and large agencies. Rates vary with experience, overhead, demand, and the level of senior attention included.</p><p>A local partner can be valuable when neighborhood context, service areas, in-person collaboration, or knowledge of the market matters. But proximity alone should not command a premium. The stronger reason to hire locally is better fit, clearer communication, and relevant understanding of the customers you want to reach.</p><p>NuvelloWeb is a founder-led Los Angeles studio. That model is designed to give small businesses direct access to the person responsible for strategy and delivery without adding layers simply to look larger.</p></section>
<section><h2>The bottom line</h2><p>For most small businesses, the right website budget is the cost of a complete solution that can be launched, owned, maintained, and used—not the cheapest number attached to a homepage.</p><p>Use <strong>$3,000–$8,000</strong> as a reasonable planning range for a focused professional website and <strong>$8,000–$20,000</strong> when the project needs deeper strategy, custom work, stronger content support, or integrations. Then compare scope, ownership, and post-launch responsibilities before comparing totals.</p><div class="article-cta"><span class="eyebrow">Planning a website?</span><h2>Get a clear scope before you commit to a number.</h2><p>Share the goal, the current site, and the constraints. We’ll help identify the smallest complete project that can move the business forward.</p><div class="actions"><a class="button orange button-arrow" href="/contact">Start a conversation</a><a class="button ghost" href="/services/web-design">Explore web design</a></div></div></section>
<section id="faqs"><span class="eyebrow">Common questions</span><h2>Small-business website cost FAQs</h2>${faq(articleFaqs)}</section>
<div class="author-card"><img src="/assets/Images/BenKrikler2.jpeg" alt="Benjamin Krikler"><div><span class="kicker">About the author</span><h3>Benjamin Krikler</h3><p>Founder of NuvelloWeb, a Los Angeles web design and digital marketing studio focused on clear strategy, direct communication, and practical digital foundations.</p><a href="/about">About NuvelloWeb</a></div></div>
<p class="article-source"><strong>Pricing note:</strong> The ranges in this guide are planning estimates, not a fixed quote. Actual project pricing depends on scope, content, platform, functionality, timing, and support requirements.</p>
</article></div></section>${form('website-cost','Web Design & Development','Let’s price the right website—not the vaguest one.')}`;

const localSeoBody = `<section class="article-hero article-hero-text"><div class="article-heading"><div class="breadcrumb"><a href="/">Home</a><span>/</span><a href="/blog">Blog</a><span>/</span>Local SEO</div><span class="eyebrow">Local SEO · Los Angeles</span><h1>${localSeoTitle}</h1><p class="lead">A straightforward plan for helping nearby customers understand what you do, where you operate, and why they should choose your business.</p><div class="article-meta"><span>By <a href="/about">Benjamin Krikler</a></span><time datetime="${localSeoPublishedDate}">${localSeoPublishedLabel}</time><span>7 minute read</span></div></div></section>
<section class="section article-section"><div class="wrap article-layout"><aside class="article-toc" aria-label="Article contents"><span class="kicker">In this guide</span><nav><a href="#foundation">The foundation</a><a href="#business-profile">Business Profile</a><a href="#website">Your website</a><a href="#reviews">Reviews</a><a href="#citations">Business listings</a><a href="#content">Local content</a><a href="#30-day-plan">30-day plan</a><a href="#measure">What to measure</a><a href="#mistakes">Common mistakes</a><a href="#faqs">FAQs</a></nav></aside><article class="article-prose">
<section id="foundation"><p class="article-lede"><strong>Local SEO is the work of making your business easier to find and trust when someone searches nearby.</strong> For a Los Angeles business, that means giving Google and potential customers consistent, useful information across your Business Profile, website, reviews, and other reputable listings.</p><div class="answer-box"><span class="kicker">Start with the basics</span><p>Google says local results are primarily based on <strong>relevance, distance, and prominence</strong>. You cannot control every part of that equation, but you can make your business information complete, accurate, and genuinely useful. <a href="https://support.google.com/business/answer/7091" rel="noopener">See Google’s local ranking guidance</a>.</p></div><p>This guide focuses on the practical foundation. It will not produce an overnight ranking jump, but it can remove common weaknesses and give future SEO work a stronger base.</p></section>
<section id="business-profile"><h2>1. Build a complete Google Business Profile</h2><p>Your Google Business Profile is often the first thing a local customer sees. Claim and verify it, then make sure every field reflects the real business.</p><ul class="check-list article-checks"><li>Use the exact business name customers know</li><li>Choose the most specific primary category</li><li>Add relevant secondary categories</li><li>Set accurate hours and holiday hours</li><li>Use the correct address or service area</li><li>Add your phone number and website</li><li>Write a clear business description</li><li>Upload current, useful photos</li></ul><p>Do not add keywords, locations, or services to the business name unless they are genuinely part of the real-world name. Google’s <a href="https://support.google.com/business/answer/3038177" rel="noopener">Business Profile guidelines</a> emphasize accurate representation.</p></section>
<section id="website"><h2>2. Make the website reinforce your local story</h2><p>Your website should make the same core facts clear: what you offer, who it is for, where you work, and how someone can contact you.</p><ol class="article-steps"><li><h3>Create a focused page for each major service</h3><p>Give important services enough detail to answer real customer questions. Avoid forcing every offering into one vague page.</p></li><li><h3>Use location naturally</h3><p>Mention Los Angeles and relevant service areas where it helps the reader. Do not repeat city names simply to increase keyword density.</p></li><li><h3>Keep contact information easy to find</h3><p>Use the same business name, phone number, and address or service-area details shown on your Business Profile.</p></li><li><h3>Strengthen the technical foundation</h3><p>Use descriptive page titles, one clear main heading, helpful internal links, fast mobile pages, and LocalBusiness structured data where appropriate. Google’s <a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" rel="noopener">SEO Starter Guide</a> is a useful reference.</p></li></ol></section>
<section id="reviews"><h2>3. Build a simple review habit</h2><p>Reviews help customers compare businesses and can strengthen local prominence. Make the request part of your normal follow-up after a successful job, visit, or purchase.</p><div class="article-callout"><h3>Keep the request honest and easy.</h3><p>Send a direct review link, invite the customer to describe their own experience, and respond professionally to both positive and negative feedback. Do not buy reviews or offer rewards that distort what customers say.</p></div><p>Consistency matters more than a one-time campaign. A steady pattern of genuine feedback is more credible to customers than a sudden burst followed by silence.</p></section>
<section id="citations"><h2>4. Keep business information consistent</h2><p>A citation is a mention of your business on another website or directory. Focus on accurate listings where customers might reasonably look: major platforms, relevant industry directories, local organizations, and professional associations.</p><p>Check the essentials on each listing: business name, phone number, website, address or service area, hours, and category. Small formatting differences are usually less important than genuinely conflicting information, duplicate listings, or an old phone number.</p></section>
<section id="content"><h2>5. Publish locally useful content</h2><p>Good local content answers questions that are easier to answer when you understand the customer, the service, and the market. It should exist because it helps someone make a decision—not merely because a city name can be added to the title.</p><ul class="check-list article-checks"><li>Explain a service and who it is best for</li><li>Answer common pricing or timing questions</li><li>Compare reasonable options</li><li>Describe a local process, requirement, or constraint</li><li>Show a completed project with useful context</li><li>Cover the neighborhoods or service areas you genuinely serve</li></ul><p>A few substantial pages are a better starting point than dozens of thin, nearly identical location pages.</p></section>
<section id="30-day-plan"><h2>A practical 30-day starter plan</h2><div class="question-stack"><div><span>01</span><p><strong>Week 1: Audit the facts.</strong> Verify the Business Profile, website, and key directory listings. Correct outdated names, phone numbers, hours, URLs, and categories.</p></div><div><span>02</span><p><strong>Week 2: Improve the website.</strong> Clarify the homepage, strengthen the most important service page, check mobile usability, and make contact information easy to find.</p></div><div><span>03</span><p><strong>Week 3: Start the review habit.</strong> Create a direct review link and a short follow-up message your team can send after a good customer experience.</p></div><div><span>04</span><p><strong>Week 4: Publish one useful local page.</strong> Answer a real customer question, add internal links, and make the next action obvious.</p></div></div></section>
<section id="measure"><h2>What to measure</h2><p>Local SEO should support business outcomes, not just a ranking report. Track a small set of signals consistently:</p><ul class="check-list article-checks"><li>Calls, messages, bookings, and form submissions</li><li>Google Business Profile interactions</li><li>Organic visits to service and location pages</li><li>Search queries that bring qualified visitors</li><li>Review volume, recency, and response rate</li><li>Conversions from organic and local traffic</li></ul><p>Use rankings as context, especially across different parts of Los Angeles, but judge progress by whether more of the right people discover and contact the business.</p></section>
<section id="mistakes"><h2>Common local SEO mistakes</h2><ul class="article-steps"><li><h3>Using inconsistent or inaccurate details</h3><p>Old phone numbers, duplicate profiles, and conflicting hours create friction for search engines and customers.</p></li><li><h3>Creating thin neighborhood pages</h3><p>Changing only the city or neighborhood name does not create a useful page. Each page needs a distinct reason to exist.</p></li><li><h3>Ignoring the website</h3><p>A complete Business Profile cannot compensate for an unclear, slow, or untrustworthy website.</p></li><li><h3>Chasing shortcuts</h3><p>Keyword-stuffed names, purchased reviews, and low-quality directory packages can create more risk than value.</p></li><li><h3>Measuring only rankings</h3><p>Visibility matters, but qualified calls, inquiries, bookings, and revenue are closer to the actual goal.</p></li></ul></section>
<section><h2>The bottom line</h2><p>A strong local search foundation is not mysterious. Keep the business facts accurate, build a genuinely useful profile and website, earn honest reviews, maintain reputable listings, and publish content that answers local customer questions.</p><p>Start with the pieces you control, improve them consistently, and measure whether visibility turns into meaningful conversations.</p><div class="article-cta"><span class="eyebrow">Need a clearer local search foundation?</span><h2>Turn the checklist into a focused plan.</h2><p>NuvelloWeb can review your website, Business Profile, and local search signals, then prioritize the work most likely to help the right Los Angeles customers find you.</p><div class="actions"><a class="button orange button-arrow" href="/contact">Start a conversation</a><a class="button ghost" href="/services/seo">Explore SEO services</a></div></div></section>
<section id="faqs"><span class="eyebrow">Common questions</span><h2>Local SEO FAQs</h2>${faq(localSeoFaqs)}</section>
<div class="author-card"><img src="/assets/Images/BenKrikler2.jpeg" alt="Benjamin Krikler"><div><span class="kicker">About the author</span><h3>Benjamin Krikler</h3><p>Founder of NuvelloWeb, a Los Angeles web design and digital marketing studio focused on clear strategy, direct communication, and practical digital foundations.</p><a href="/about">About NuvelloWeb</a></div></div>
<div class="article-sources"><span class="kicker">Official resources</span><ul class="source-list"><li><a href="https://support.google.com/business/answer/7091" rel="noopener">Tips to improve your local ranking on Google</a></li><li><a href="https://support.google.com/business/answer/3038177" rel="noopener">Guidelines for representing your business on Google</a></li><li><a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" rel="noopener">Google Search SEO Starter Guide</a></li><li><a href="https://developers.google.com/search/docs/appearance/structured-data/local-business" rel="noopener">Local business structured data documentation</a></li></ul></div>
</article></div></section>${form('local-seo-guide','SEO','Let’s make your local search foundation clear.')}`;

writeFileSync(join(root, 'about.html'), shell({title:'About NuvelloWeb | Los Angeles Web Design Studio',description:'Meet NuvelloWeb, a founder-led Los Angeles studio for web design, development, SEO, branding, and digital marketing.',path:'/about',current:'about',body:aboutBody}));
writeFileSync(join(root, 'services.html'), shell({title:'Web Design & Digital Marketing Services | NuvelloWeb LA',description:'Explore web design, SEO, UI/UX, digital marketing, e-commerce, and website maintenance services from NuvelloWeb in Los Angeles.',path:'/services',current:'services',body:serviceHubBody}));
writeFileSync(join(root, 'contact.html'), shell({title:'Contact NuvelloWeb | Los Angeles Web Design Quote',description:'Contact NuvelloWeb in Los Angeles for a clear, no-pressure conversation about web design, SEO, e-commerce, or digital marketing.',path:'/contact',current:'contact',body:contactBody}));
writeFileSync(join(root, 'faq.html'), shell({title:'NuvelloWeb FAQ | Web Design, Pricing & Process',description:'Answers about NuvelloWeb website projects, platforms, pricing, ownership, timelines, SEO, and post-launch support.',path:'/faq',current:'about',body:faqBody,faqSchema:faqJson(generalFaqs)}));
writeFileSync(join(root, 'blog.html'), shell({title:'NuvelloWeb Blog | Web Design, SEO & Digital Strategy',description:'Practical guidance from NuvelloWeb on web design, SEO, digital marketing, e-commerce, and building a stronger digital foundation.',path:'/blog',current:'blog',body:blogBody}));
mkdirSync(join(root, 'blog'), { recursive: true });
writeFileSync(join(root, 'blog', `${articleSlug}.html`), shell({title:articleTitle,description:articleDescription,path:articlePath,current:'blog',body:articleBody,faqSchema:faqJson(articleFaqs),article:{image:articleImage,imageWidth:1800,imageHeight:1201,datePublished:articlePublishedDate,section:'Web Design',keywords:['small-business website cost','Los Angeles web design pricing','website budget','web design proposal']},ogImage:articleImage,ogWidth:1800,ogHeight:1201}));
writeFileSync(join(root, 'blog', `${localSeoSlug}.html`), shell({title:localSeoTitle,description:localSeoDescription,path:localSeoPath,current:'blog',body:localSeoBody,faqSchema:faqJson(localSeoFaqs),article:{datePublished:localSeoPublishedDate,section:'SEO',keywords:['local SEO','Los Angeles local SEO','Google Business Profile','local search']}}));
for (const s of services) writeFileSync(join(root, 'services', `${s.slug}.html`), shell({title:`${s.name} in Los Angeles | NuvelloWeb`,description:`${s.name} for Los Angeles businesses. Clear strategy, thoughtful execution, direct communication, and practical next steps.`,path:`/services/${s.slug}`,current:'services',body:serviceBody(s),faqSchema:faqJson(s.faqs),serviceName:s.name}));

// Google Drive created these identical “2” copies during a sync conflict.
// Keep harmless redirect stubs so old encoded URLs cannot expose stale content.
const duplicateRedirects = [
  ['index 2.html', '/'], ['about 2.html', '/about'], ['services 2.html', '/services'],
  ['contact 2.html', '/contact'], ['faq 2.html', '/faq'],
  ...services.filter(s => s.slug !== 'maintenance').map(s => [`services/${s.slug} 2.html`, `/services/${s.slug}`])
];
for (const [file, target] of duplicateRedirects) writeFileSync(join(root, file), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${target}"><link rel="canonical" href="${domain}${target}"><meta name="robots" content="noindex"><title>Redirecting…</title></head><body><p><a href="${target}">Continue to NuvelloWeb</a></p></body></html>`);
